### ISSUE TITLE
xlnx-3.19 dependancies

### ISSUE THREAD

**Issue by johnnymopo** [bperez77/xilinx_axidma#14]
I am using Petalinux 2015.2 (xlnx-3.19 kernel).  I found these issues and did a quick hack as I do not use VDMA:

struct xilinx_vdma_config has no member vsize, hsize, stride
       I commented out all assignments to xilinx_vdma_config
XILINX_DMA_IP_VDMA undeclared
       I commented out conditional and assigned XILINX_DMA_IP_DMA
 DMA_COMPL_SKIP_DEST_UNMAP undeclared 
       ( 1 << 3 ) in another kernel

This resulted in a successful (untested) build

**Comment by bperez77** [comment]
Unfortunately, I haven't figured out a good way to deal with this. Originally, I thought I could by casing on the Linux version number. Originally, the 3.x kernels had those fields, and the 4.x kernel had those removed. However, it appears that some of the 4.x patches were backported to 3.x kernels, leading to this issue.

I guess I could add a patch for people to apply to fix this. Could you upload the patch of your changes?
