### ISSUE TITLE
Unable to handle kernel NULL pointer dereference at virtual address 00000000

### ISSUE THREAD

**Issue by Cuty-pink** [bperez77/xilinx_axidma#153]
According to the operations in the readme, I generated a .ko file and an App file. However, when I tried to load the driver on the development board, I encountered an error. Can you help me figure out what the problem is?
![YSV {7EC~MB~1ZDC}(93CY8](https://github.com/bperez77/xilinx_axidma/assets/83273989/c911646c-5d89-4901-ac4b-b2b59e5d5f6a)

**Comment by hamidrmt** [comment]
I have same issue, You should enable two dma channels and give right device-id to dma channels in dts file and dmas property in chrdev should start with 0:
dmas = <&axi_dma_0 0 &axi_dma_0 1> correct
dmas = < &axi_dma_0 1> not correct

**Comment by Cuty-pink** [comment]
You are right! Thanks for your suggest!

**Comment by WalkingSeason** [comment]
I have another solution, for builds that axidma doesn't have channel 0. I commented out lines 98-100 of /driver/axidma_of.c :
```c
    // if (channel == 1) {
        // dma_chan_node = of_get_next_child(dma_node, dma_chan_node);
    // }
```

then it works well.

![image](https://github.com/bperez77/xilinx_axidma/assets/61611215/700cc2c1-b8c7-4bbd-b6b8-44904e2adccb)

Here is my device-tree:

```device-tree
&amba_pl{

    /* Comaptible point for axidma for bmperez axidma drivers */
    axidma_chrdev: axidma_chrdev@0 {
        compatible = "xlnx,axidma-chrdev";
        dmas = <&axi_dma_2 0 &axi_dma_3 0 &axi_dma_0 1 &axi_dma_1 1>;
        dma-names = "dma2", "dma3", "dma0", "dma1";
    };
}
```

**Comment by wangzhenhua92429** [comment]
你发给我的邮件已收到！                                ——王振华
