### ISSUE TITLE
Possible member omission in axidma_request_channels()

### ISSUE THREAD

**Issue by iainmarcuson** [bperez77/xilinx_axidma#23]
In axidma_request_channels() line 645, the if statement compares variable chan to NULL.  From looking at some of the kernel code, it looks a check on chan->chan should be done, since chan is dereferenced in the previous line.

**Comment by bperez77** [comment]
Good catch, I should be checking `chan->chan` instead of `chan`. Probably wasn't the best idea to give the variable the same name as a field of the struct.
