### ISSUE TITLE
Erorr in axidma_setup_vdma_config(struct xilinx_vdma_config *dma_config)  function

### ISSUE THREAD

**Issue by sploet** [bperez77/xilinx_axidma#28]
Have a look  at the file axidma_dma.c for the function "static void axidma_setup_vdma_config (*******):

> 
> // Setup the config structure for VDMA
> 
> static void axidma_setup_vdma_config(struct xilinx_vdma_config *dma_config)
> {
>     memset(dma_config, 0,  sizeof(dma_config));
> 
>     dma_config->frm_dly = 0;            // Number of frames to delay
>     dma_config->gen_lock = 0;           // Genlock, VDMA runs on fsyncs
>     dma_config->master = 0;             // VDMA is the genlock master
>     dma_config->frm_cnt_en = 1;         // Interrupt based on frame count
>     dma_config->park = 0;               // Continuously process all frames
>     dma_config->park_frm = 0;           // Frame to stop (park) at (N/A)
>     dma_config->coalesc = 1;            // Interrupt after one frame completion
>     dma_config->delay = 0;              // Disable the delay counter interrupt
>     dma_config->reset = 0;              // Don't reset the channel
>     dma_config->ext_fsync = 0;          // VDMA handles synchronizes itself
>     return;
> }
> 
I think that string 

    **memset(dma_config, 0, sizeof(dma_config));**

is needed for the cleaning a "struct dma_config", so you have to provide the size of the struct, something like this:

    **memset(dma_config, 0, sizeof(struct xilinx_vdma_config));**

BTW, My Respect for software your created. It is really cool.
I am trying to run it on the zynq ultrascale+ and have some issues.
Look at here please:  https://github.com/bperez77/xilinx_axidma/issues/27

**Comment by bperez77** [comment]
Thanks, and good catch! I'll be pushing up your fix in a moment.
