### ISSUE TITLE
Offset of a user space virtual address is ignored

### ISSUE THREAD

**Issue by Baum55** [bperez77/xilinx_axidma#49]
I call the function "axidma_oneway_transfer()" from the lib in my application and I wanted to add an offset to the buffer.
I have 2 threads. 1 thread who reads the data from the FPGA and another thread who process the data.
To make sure that the processed data are not overridden, I wanted to add an offset to the allocated buffer.
First I read to buf, then to buf + offset, then to buf + 2*offset and so on.

For example:
``
char* buf = (char*)axidma_malloc(axidma_dev, 100);
``
``
axidma_oneway_transfer(axidma_dev, rx_chans->data[0], buf + 10, 10, true);
``

But the data are always written to the base address of buf and not buf + offset (in the example: buf + 10).
Is this the desired behavior?

**Comment by bperez77** [comment]
Yep, that's definitely a bug in the driver. I forgot to add in the offset from the base address that you pass in with the function. I should have fix up fairly quickly.

**Comment by Baum55** [comment]
That's great to hear. Thank you.

**Comment by bperez77** [comment]
Ok, I just pushed a change that should fix it. Can you let me know if that does the trick? I unfortunately don't have a test setup to verify the change.

**Comment by Baum55** [comment]
No, it does not work. You add the offset only in the second case to the return addresse.
I have a issue with your commit "Changed the include for `send_sig_info`. "

I will test it intensive and give you the changes with a pull request.

**Comment by bperez77** [comment]
Ahh crap, that's what I get for making a quick change like that. I'll look over the PR.
