### ISSUE TITLE
Missing dma_set_coherent_mask()

### ISSUE THREAD

**Issue by corna** [bperez77/xilinx_axidma#58]
According to the [kernel guide](https://www.kernel.org/doc/Documentation/DMA-API-HOWTO.txt) ("DMA addressing limitations" section), `dma_set_coherent_mask()` **must** be used to check (and set) the DMA addressing mask before allocating the memory with `dma_alloc_coherent()`. This seems to be enforced in 4.14, as the allocation fails (`dma_alloc_coherent()` returns `NULL`) and a kernel print a warning "coherent DMA mask is unset". 

Inserting something like this

```
    if (dma_set_coherent_mask(dev->device, DMA_BIT_MASK(32)))
    {
        axidma_err("Bad mask.\n");
        goto device_cleanup;
    }
```

at the end of `axidma_chrdev_init()` fixes the issue.

**Comment by bperez77** [comment]
Good catch! I'll add this fix later tomorrow.
