### ISSUE TITLE
DMA receive transaction timed out

### ISSUE THREAD

**Issue by rdb9879** [bperez77/xilinx_axidma#59]
When running the benchmark example on petalinux 2017.4, I am getting "axidma: axidma_dma.c: axidma_start_transfer: 305: DMA receive transaction timed out". 

the insmod ./xilinx-axidma.ko command seems to be working correctly: "DMA: Found 1 transmit channels and 1 receive channels".

My Vivado block design simply has a AXI_DMA ip looped back onto itself, with the two interrupts hooked up to the IRQ_F2P (mm2s_introut on bit 0, s2mm_introut on bit 1). Other than that, everything was setup with the auto-complete stuff in Vivado.

 Should the driver and example apps work with any settings of the AXI_DMA IP? I have the following settings:

Enable Scatter Gather Engine (checked)
Enable Micro DMA (not checked)
Enable Multi Channel Support (not checked)
Enable Control/Status Stream (not checked)
Width of Buffer Length Register: 23
Address Width: 32
Enable Read Channel (checked)
Number of Channels (Read, 1)
Memory Map Data Width (Read, 32)
Stream Data Width (Read, 32)
Max Burst Size (Read, 16)
Allow Unaligned Transfers (Read, checked)
Enable Write Channel (checked)
Number of Channels (Write, 1)
Memory Map Data Width (Write, 32)
Stream Data Width (Write, 32)
Max Burst Size (Write, 16)
Allow Unaligned Transfers (Write, checked)

Does anything look incorrect with this setup? I did see Issue #43 , but it looks like the solution to this was to enable Scatter Gather, which I have already done.

**Comment by bperez77** [comment]
The driver should work with any settings of the AXI DMA IP, except for multi-channel mode, which is currently not supported by the driver. Also, as far as I can tell, the setting you have look pretty standard.

A timeout issue is pretty common and it essentially means that something is incorrectly configured in the system. However, the cause can be a whole myriad of things, so can you provide the following for me:

   1. The output of the `dmesg` command immediately after running the benchmark program (please attach this as a file).
   2. The relevant device tree nodes pertaining to the AXI DMA IP and this driver. If you're not sure how to get these (since they were auto-generated), feel free to instead attach the .dtb file.

**Comment by rdb9879** [comment]
Here are the requested data dumps. I had to add a ".txt" to the dtb file because dtb was an unsupported upload type.


[system.dtb.txt](https://github.com/bperez77/xilinx_axidma/files/2054082/system.dtb.txt)
[dmesg.txt](https://github.com/bperez77/xilinx_axidma/files/2054083/dmesg.txt)

**Comment by bperez77** [comment]
Everything looks find in your `dmesg` output and in the device tree that you sent me. What FPGA device are you using?

The typical cause of timeouts is that the either that the interrupts from the AXI DMA IP are no hooked up correctly or not specified correctly in the device tree or the width of the buffer length register is set to too low of a value. Can you attach the block diagram of your design (preferrably in PDF or image format)?

**Comment by rdb9879** [comment]
I'm using the Avnet Microzed board which has a XC7Z010-1CLG400C FPGA. I have attached the block diagram as a PDF. Thanks for the support.
[VivadoBlockDiagram.pdf](https://github.com/bperez77/xilinx_axidma/files/2055560/VivadoBlockDiagram.pdf)

**Comment by bperez77** [comment]
Interesting, there isn't anything in your Block Diagram that points to being the cause of the timeout. I'm stumped as to why you're seeing a timeout.

One other thing we can try is enabling the AXI DMA Test driver that's part of the Linux kernel. That should confirm if the problem is in this driver, or outside of it.

**Comment by rdb9879** [comment]
I have now tested with the AXI DMA Test driver that is part of the Linux kernel. What I found is that the AXI DMA Test driver does not completely successfully with my current block diagram settings. After troubleshooting and hunting around online, I finally managed to get it to work with the following settings:

	Enable Scatter Gather Engine
	Wide of Buffer Length Register: 23
	Address Width: 32
	Enable Read Channel
		Memory Map Data Width: 64
		Stream Data Width : 64
		Max Burst Size: 16
		Allow Unaligned Transfers
	Enable Write Channel
		Memory Map Data Width: 64
		Max Burst Size: 16
		Allow Unaligned Transfers
	Everything else off

In addition to this, I had to change the AXI HP settings to 64 bits within the Zynq block:
AXI HP0 DATA WIDTH to 64

After this, not only did the Linux Test DMA work, but now the xilinx_axidma benchmark test is running successfully:

AXI DMA Benchmark Parameters:
        Transmit Buffer Size: 7.91 Mb
        Receive Buffer Size: 7.91 Mb
        Number of DMA Transfers: 1000 transfers

Using transmit channel 0 and receive channel 1.
Single transfer test successfully completed!
Beginning performance analysis of the DMA engine.

DMA Timing Statistics:
        Elapsed Time: 10.52 s
        Transmit Throughput: 751.79 Mb/s
        Receive Throughput: 751.79 Mb/s
        Total Throughput: 1503.57 Mb/s

**Comment by bperez77** [comment]
Great, glad to hear you got it working. What exactly did you change from the original settings that got it to work? Just so that others who look over this post will be able to figure out what went wrong.

**Comment by rdb9879** [comment]
It was simply changing the block diagram settings. No idea why this worked, but it did.

**Comment by bperez77** [comment]
Right, I was more curious which settings actually changed between your AXI DMA settings and the new ones. It looks like the only things that were changed were the *Memory Map Data Width* and *Stream Data Width* for the read and write channels.
