### ISSUE TITLE
Generalize the Transfer Function to Properly Support VDMA

### ISSUE THREAD

**Issue by bperez77** [bperez77/xilinx_axidma#62]
Currently, the transfer function does not fully support VDMA; it currently hard codes the frame size to 1920x1080x4. In order to properly generalize this functionality, a struct should be added that can be used to set the frame size from the library call.

This is a follow up from issue #61.

**Comment by bperez77** [comment]
@tthhbb Can you verify that this changes work for the issue you had in #61, when you get a chance?

**Comment by tthhbb** [comment]
Unfortunately I cannot try it anymore, because the work was for a university project and I already had to return the Zybo. But as the only problem was the hard coded frame size I suppose your changes solve the issue.
