### ISSUE TITLE
How to build dma-driver with petalinux

### ISSUE THREAD

**Issue by feng007liu** [bperez77/xilinx_axidma#89]
When I try to build the drvier according to your instructions, there were some mistakes :
1. Since I have delete the automatically generated xilinx-axidma.c, a tips about "unable to get checksum for xilinx-axidma SRC_URI entry ....." appeared, and I delete the SRC_URI line in the xilinx-axidma.bb, and got the error as shown below:
2.ERROR:xilinx-axidma-1.0-r0 do_compile: oe_runmake failed

Please advice if someone have a little spare time.
Thank you very much!

**Comment by honorpeter** [comment]
@feng007liu Do you succeed. how to build dma-driver with petalinux  .could you advice if you have a little spare time
