### ISSUE TITLE
2018.2 Petalinux AXIDMA Config options

### ISSUE THREAD

**Issue by pmccumber** [bperez77/xilinx_axidma#94]
The notes suggest enabling these:

CONFIG_XILINX_AXIDMA=y
CONFIG_XILINX_AXIVDMA=y

I did not see these in the config file.   What do these options do in the kernel?  I intend to simply add them.

**Comment by pmccumber** [comment]
If these options are gone in 2018.2, how does that affect this driver?

**Comment by xmentos** [comment]
You could use `petalinux-config -c kernel` to activate these

**Comment by pmccumber** [comment]
Yes.  That's what I did.  Those options still are not present in the version we are using (2018.2).   There are analogous ones but was curious how it might affect the driver.

**Comment by tpeshkin** [comment]
Seems these config options are obsolete, to allow DMA transfers enable following option:

> menuconfig XILINX_DMA_ENGINES
>         bool "Xilinx DMA Engines"
>         help
>           Enable support for the Xilinx DMA controllers. It supports three DMA
>           engines: Axi Central DMA (memory to memory transfer), Axi DMA (memory and
>           device transfer), and Axi VDMA (memory and video device transfer).
>

**Comment by honorpeter** [comment]
> menuconfig XILINX_DMA_ENGINES
@tpeshkin But how to do and in where place ?

**Comment by tpeshkin** [comment]
petalinux-config -c kernel
 Device Drivers ---> [ * ] DMA Engine support ---> [ * ] Xilinx DMA Engines
