### ISSUE TITLE
 Assertion `0 <= siginfo->si_int && siginfo->si_int < axidma_dev.num_channels' failed.

### ISSUE THREAD

**Issue by SimonLeeCHN** [bperez77/xilinx_axidma#99]
Hi,
the examples run well on my dma loop design
but when i tried to change the dma channels device-id the example axidma_transfer thow an error

```
AXI DMA File Transfer Info:
Transmit Channel: 4
Receive Channel: 3
Input File Size: 0.00 MiB
Output File Size: 0.00 MiB

axidma_transfer: library/libaxidma.c:193: axidma_callback: Assertion `0 <= siginfo->si_int && siginfo->si_int < axidma_dev.num_channels' failed.
```
i changed the s2mm dma channel to 3,mm2s dma channel to 4,the error occurred
![{VJD3)@} TQ~GI$CQM$A`09](https://user-images.githubusercontent.com/22796085/57784575-b3e2db00-7762-11e9-85e1-9308e383927b.png)

but if i change the s2mm dma channel to 0,mm2s dma channel to 1,it works well
![JG`IQF)}D(8~RS36WS JY3P](https://user-images.githubusercontent.com/22796085/57784478-87c75a00-7762-11e9-8562-0f80b1d61e4e.png)

did i made a mistake in change the id?

**Comment by GOOD-Stuff** [comment]
Hello! 
May be it's because in your axidma_chrdev in dmas set for 0 and 1 channels. 
If you change device-id in channels, you also have to change this IDs in axidma_chrdev.
So, you must set dmas like `= <0x7 0x4 0x7 0x3>.`
For more information, I advice to look on [axidma_of.c](https://github.com/bperez77/xilinx_axidma/blob/master/driver/axidma_of.c)

**Comment by SimonLeeCHN** [comment]
Thanks GOOD-Stuff
i was follow the steps in the README.md,so i thought the device-id can be arbitrary
![image](https://user-images.githubusercontent.com/22796085/58861231-7c6faa80-86e0-11e9-9ff1-f93069437dfa.png)

**Comment by GOOD-Stuff** [comment]
Hi SimonLeeCHN!

Did my advice helps to solve your problem? If so, can you please close this issue :)
